server:
  port: 8999
    

  
eureka:
  instance:
     hostname: localhost 
     
spring:
  application:
     name: api-gateway  
  cloud:
     gateway:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                 - Path=/user/**
              filters:
                 - name: CircuitBreaker
                   args:
                       name: user-service
                       fallbackuri: forward:/userServiceFallback
                       
                 
                 
                 
                 
                 
            - id: contact-service
              uri: lb://contact-service
              predicates:
                 - Path=/contact/**
              filters:
                 - name: CircuitBreaker
                   args:
                       name: contact-service
                       fallbackuri: forward:/contactServiceFallback
                       
                       
            - id: hystrix-dashboard
              uri: lb://hystrix-dashboard
              predicates:
                 - Path=/hystrix/**
              filters:
                 - name: CircuitBreaker
                   args:
                       name: hystrix-dashboard
                       fallbackuri: forward:/hystrixDashboardServiceFallback
                       

hystrix:
     command:
        fallbackcmd:
           execution:
              isolation:
                 thread:
                  timeoutInMilliseconds: 5000
                
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
              

    
   